cargo_env = "Development"
rust_log = "debug"

app_host = "127.0.0.1"
app_port = 5000

[db]
uri = "mongodb://root:root@localhost:27017"
database = "rust-axum-boilerplate-db"

[jwt]
access_token_secret = "ddd26ab8c5140fb0dc5bd8cdccd6a0102d09c9bdf2466a5cd718373fd42a17b1"
access_token_expiry = 3600
refresh_token_secret = "bdca01f8df0bfba0e400f3daf3e629118b76fe8b15d7362bbabb57496a30bdfc"
refresh_token_expiry = 604800

[log]
file_name = "app.log"
rolling = "daily"